### ISSUE TITLE
Difference between code and paper

### ISSUE THREAD

**Issue by 123456789asdfjkl** [Ivan-Tang-3D/Point-PEFT#1]
您好！非常感谢您的杰出工作！您论文中前L个Stage使用的Point-prior Prompt， 后（N-L）Stage不使用Prompt，但是看您的代码实现[Point_Mask_Rev_FT_scan.py](https://github.com/Ivan-Tang-3D/Point-PEFT/blob/main/models/Point_Mask_Rev_FT_scan.py)，Prompt是始终使用的，在后几个Stage加入的Point-prior Prompt。好像与论文说的不一样，想问您一下我代码理解的是对的吗？

**Comment by Ivan-Tang-3D** [comment]
The L is different for models and Downstream Tasks. In ScanObjectNN, for Point-M2AE, L is 12. Please Refer to the 4.1.1 and 4.1.2 sections in my paper.

**Comment by Ivan-Tang-3D** [comment]
> 您好！非常感谢您的杰出工作！您论文中前L个Stage使用的Point-prior Prompt， 后（N-L）Stage不使用Prompt，但是看您的代码实现[Point_Mask_Rev_FT_scan.py](https://github.com/Ivan-Tang-3D/Point-PEFT/blob/main/models/Point_Mask_Rev_FT_scan.py)，Prompt是始终使用的，在后几个Stage加入的Point-prior Prompt。好像与论文说的不一样，想问您一下我代码理解的是对的吗？

The L is different for models and Downstream Tasks. In ScanObjectNN, for Point-M2AE, L is 12. Please Refer to the 4.1.1 and 4.1.2 sections in my paper.

**Comment by 123456789asdfjkl** [comment]
我知道L针对不同的数据集和任务时改变的，我想问您的是代码里Prompt是一直有的，Point-prior Prompt是插入到最后一个Stage中的，好像跟论文的图2不一样。图2是在前L个层插入Point-prior Prompt，后面的层不使用Prompt

![image](https://github.com/Ivan-Tang-3D/Point-PEFT/assets/45223476/d739add5-b0ae-4805-8293-0b1e03bf4465)

**Comment by Ivan-Tang-3D** [comment]
> > 我知道L针对不同的数据集和任务时改变的，我想问您的是代码里Prompt是一直有的，Point-prior Prompt是插入到最后一个Stage中的，好像跟论文的图2不一样。图2是在前L个层插入Point-prior Prompt，后面的层不使用Prompt
> > ![image](https://private-user-images.githubusercontent.com/45223476/296765462-d739add5-b0ae-4805-8293-0b1e03bf4465.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjU1NzQsIm5iZiI6MTcwNTMyNTI3NCwicGF0aCI6Ii80NTIyMzQ3Ni8yOTY3NjU0NjItZDczOWFkZDUtYjBhZS00ODA1LTgyOTMtMGIxZTAzYmY0NDY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDEzMjc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNWRlZTlkMDEzZDQzNWE0NzRhNDY1Mzc1NThlZmQ2MGJlYzJiOGM2ZDQ4ZGNjOWU5MTcyNjEwOWQ3ZDlkOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wY3zLoIhT1IS8XhnobwiITPOgIB0yqXkdkmQaNvCQQs)
> 

 I'm sorry, the paper is not clear about this aspect. L is targeted for Prompt tokens. The Point-Prior Prompt is only applied in the last stage in Point-M2AE. So the L is 12 for Point-M2AE, which ensures the point-prior prompt for last stage. This derives the faster training and fewer parameters

**Comment by 123456789asdfjkl** [comment]
我明白了，感谢您的解答 ！@Ivan-Tang-3D

**Comment by Ivan-Tang-3D** [comment]
> 我明白了，感谢您的解答 ！@Ivan-Tang-3D

You are Welcome.
